name: Build VUE App ğŸ› ï¸

on:
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  pages_deploy:
    # Defines the deployment environment and URL for the GitHub Pages deployment.
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    # if: contains(github.event.head_commit.message, 'deploy') || contains(github.event.head_commit.message, 'publish')

    steps:
      - name: Checkout code ğŸ‘€
        uses: actions/checkout@v3

      # Set up Node.js environment with a specific version (22).
      - name: Set up Node.js ğŸ› ï¸
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies ğŸ“¦
        working-directory: ./ # Specify the folder where the app code resides (./client for fullstack applications).
        run: npm ci # Clean install of the project's dependencies.

      - name: Download Drive Images ğŸ“¥
        working-directory: ./
        env:
          GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          GOOGLE_DRIVE_ID: ${{ secrets.GOOGLE_DRIVE_ID }}
        run: npm run download-gallery

      # Process gallery images to generate thumbnails and blur hashes
      - name: Process Gallery Images ğŸ–¼ï¸
        working-directory: ./
        run: npm run process-images

      # Build the VUE application
      - name: Build the app ğŸ—ï¸
        working-directory: ./
        run: npm run build # Runs the 'build' script defined in the package.json file

      # Configure the GitHub Pages deployment
      - name: Setup Pages ğŸ“ƒ
        uses: actions/configure-pages@v4

      # Uploads the build output for deployment to GitHub Pages.
      - name: Upload artifact â¬†ï¸
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docs" # Path to the built app's static files, this can be configured in the `vite.config` file with 'outputDir'

      # Deploy the application to GitHub Pages using the 'deploy-pages' pre-build action.
      - name: Deploy to GitHub Pages âœ¨
        id: deployment
        uses: actions/deploy-pages@v4
